
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int allave = 16;
  public static final int suma = 2;
  public static final int cllave = 15;
  public static final int resta = 8;
  public static final int interrogacionC = 7;
  public static final int interrogacionA = 6;
  public static final int con = 32;
  public static final int hasta = 31;
  public static final int hasta_que = 37;
  public static final int disyuncion = 4;
  public static final int coma = 9;
  public static final int entonces = 23;
  public static final int identificador = 46;
  public static final int pasito = 33;
  public static final int fin_funcion = 43;
  public static final int inicio = 20;
  public static final int comillasd = 19;
  public static final int caracter = 48;
  public static final int repetir = 38;
  public static final int fin_metodo = 41;
  public static final int si = 22;
  public static final int mientras = 35;
  public static final int comillasimple = 18;
  public static final int fin_si = 26;
  public static final int porcentaje = 11;
  public static final int fin_mientras = 36;
  public static final int EOF = 0;
  public static final int para = 30;
  public static final int error = 1;
  public static final int fin_para = 34;
  public static final int mayor = 14;
  public static final int metodo = 40;
  public static final int por = 3;
  public static final int punto = 5;
  public static final int funcion = 42;
  public static final int dospuntos = 12;
  public static final int fin_segun = 29;
  public static final int segun = 27;
  public static final int hacer = 28;
  public static final int fin = 21;
  public static final int de_lo_contrario = 24;
  public static final int salto = 17;
  public static final int puntocoma = 13;
  public static final int retornar = 39;
  public static final int o_si = 25;
  public static final int ejecutar = 44;
  public static final int digito = 47;
  public static final int colocho = 10;
  public static final int cadena = 45;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "suma",
  "por",
  "disyuncion",
  "punto",
  "interrogacionA",
  "interrogacionC",
  "resta",
  "coma",
  "colocho",
  "porcentaje",
  "dospuntos",
  "puntocoma",
  "mayor",
  "cllave",
  "allave",
  "salto",
  "comillasimple",
  "comillasd",
  "inicio",
  "fin",
  "si",
  "entonces",
  "de_lo_contrario",
  "o_si",
  "fin_si",
  "segun",
  "hacer",
  "fin_segun",
  "para",
  "hasta",
  "con",
  "pasito",
  "fin_para",
  "mientras",
  "fin_mientras",
  "hasta_que",
  "repetir",
  "retornar",
  "metodo",
  "fin_metodo",
  "funcion",
  "fin_funcion",
  "ejecutar",
  "cadena",
  "identificador",
  "digito",
  "caracter"
  };
}

